---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: data-volume-NUM
  namespace: personio
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hdd 
  gcePersistentDisk:
    pdName: pd-hdd-disk-NUM 

